const HTTP_STATUS = {
  REQUEST_ERROR: 0,
  OK: 200,
  ERROR_THRESHOLD: 400,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  NOT_ACCEPTABLE: 404,
  CONFLICT: 409,
  SERVER_ERROR: 500
}

const HTTP_MESSAGES = {
  REQUEST_ERROR: 'Request Error',
  OK: 'OK',
  BAD_REQUEST: 'Bad HTTP Request',
  UNAUTHORIZED: 'Unauthorized Access',
  FORBIDDEN: 'Forbidden',
  NOT_FOUND: 'Not Found',
  NOT_ACCEPTABLE: 'Not Acceptable',
  CONFLICT: 'Conflict',
  SERVER_ERROR: 'Unknown Exception'
}

module.exports = {
  HTTP_STATUS: HTTP_STATUS,
  HTTP_MESSAGES: HTTP_MESSAGES
}
